### ISSUE TITLE
Writing compressed multipage TIFF

### ISSUE THREAD

**Issue by WowMuchName** [haraldk/TwelveMonkeys#334]
There is either a bug or need for additional clarification with the tiff-plugin when writing multiple pages is combined with compression.

https://gist.github.com/WowMuchName/23b80df8cb54917fac0b338f1e3ea245

**Expected:**

A tiff is created with two pages:

![image0](https://cloud.githubusercontent.com/assets/13510843/24246304/0ee1974a-0fc7-11e7-9e7e-1acee2c56b63.png)

![image1](https://cloud.githubusercontent.com/assets/13510843/24246312/148489d2-0fc7-11e7-9a1e-6c860fa3ea75.png)

**Received**

A tiff with two pages:

![image0](https://cloud.githubusercontent.com/assets/13510843/24246369/4e1c6c3c-0fc7-11e7-8655-b8fa49cd47ea.png)

![image1](https://cloud.githubusercontent.com/assets/13510843/24246373/52650c72-0fc7-11e7-89f5-457024868abd.png)

**Additional information**

The pages after one seem always wrong. When using real images, they are not always completely black but always messed up with black bars all over the place. They are displayed like that in windows-image viewer and irfan view. Also reading the file-data back into java contains the same error after page one. 

When I remove the lines 34-35 (where group4 compression is set) the multitiff is okay. Using LZW instead of CCITT T.6 emitts a result which is also invalid and causes an exception when trying to read it in java.

It seems that combining multitiff + compression is either not working correctly or there is need for additional documentation. In JAI from which we are migrating I can't recall ever needing anything apart from setCompressionMode and setCompressionType to achieve the desired compression for multitiffs. If additional steps are needed in twelvemonkeys an example, testcase or additional documentation which shows how to write multitiffs with compression would be helpfull.

**Comment by haraldk** [comment]
Hi,

What version of the library are you using? Are you using a prebuilt version or do you build from source?

Anyway, I'll look into this as soon as possible and see if I can figure it out. The idea is that the TwelveMonkeys TIFF plugin should work as much as possible identical to the JAI version.

Note that there's a known issue with some software misinterpreting the output of CCITT encoded images in PhotometricInterpretation: BlackIsZero (they assume WhiteIsZero, regardless). The plugin does output this correctly, but I'm considering changing the behavior so that the default is WhiteIsZero (and at least not converting images that originally was WhiteIsZero), just to be more compatible with existing software.

-- 
Harald K

**Comment by haraldk** [comment]
At first sight, there seems to be something wrong with the byte offsets/byte counts in the consecutive pages. I'll investigate further, and hopefully find a fix.

Thanks for reporting and providing a test case!

-- 
Harald K

**Comment by WowMuchName** [comment]
Hi Harald,

**thank you** for taking the time to provide quality software to the community.

We are using the maven jars:
com\twelvemonkeys\imageio\imageio-core\3.3.2\imageio-core-3.3.2.jar
com\twelvemonkeys\common\common-lang\3.3.2\common-lang-3.3.2.jar
com\twelvemonkeys\common\common-io\3.3.2\common-io-3.3.2.jar
com\twelvemonkeys\common\common-image\3.3.2\common-image-3.3.2.jar
com\twelvemonkeys\imageio\imageio-jpeg\3.3.2\imageio-jpeg-3.3.2.jar
com\twelvemonkeys\imageio\imageio-tiff\3.3.2\imageio-tiff-3.3.2.jar
com\twelvemonkeys\imageio\imageio-psd\3.3.2\imageio-psd-3.3.2.jar
com\twelvemonkeys\imageio\imageio-pnm\3.3.2\imageio-pnm-3.3.2.jar
com\twelvemonkeys\imageio\imageio-metadata\3.3.2\imageio-metadata-3.3.2.jar

It being a problem of windows image viewer not recognizing a "subformat" correctly was my first thought. When reading the images back in java however they have the exact same fault. Either wiv, irfan view and the tiff-reader have the same flaw or the writing contains an error.

Now that you mention it there is one difference between JAI and TM that could be related.

In JAI I would do this:

`
TIFFImageWriteParam param = (TIFFImageWriteParam) tiffImageWriter.getDefaultWriteParam();
param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
param.setCompressionType("CCITT T.6");
TIFFImageMetadata metadata = tiffImageWriter.getDefaultImageMetadata(param.getDestinationType(),
						param);
` 
In TM that doesn't work. getDestinationType returns null.

So we do this:
`
param.setDestinationType(ImageTypeSpecifier.createFromRenderedImage(images.get(0)));
` 

Could createFromRenderedImage create some unexpected initial parameters for the algorithm? At any rate in JAI I don't think we ever needed to apply the destination-type manually.

**Comment by WowMuchName** [comment]
I have been doing some more digging

First of all in my example code the try blocks should be nested for this to work with JAI.

When running the example with JAI I discovered that it only produces the expected result when setDestinationType is **not** called. When setting the destination type like in the example JAI produces a tiff which according to the header (or at least windows property viewer) is CCITT T.6 while looking at it in a hex editor shows its actually uncompressed. It still works but it seems that JAI falls back to uncompressed since it doesn't like the destination type in conjunction with the compression.

This would support the idea that there is nothing wrong with the compression code but rather that the createFromRenderedImage method generates an inapplicable configuration.
Unfortunately the default destination type for JAI seems to be buried so deep in its guts that I can't find it. To rule out any miss-configuration, if we want to set the destination type manually instead of deriving it from the buffered-image, what configuration would we need for the binary image?

I've attached 3 versions of the image done with TM and JAI for comparison

[Tiffs.zip](https://github.com/haraldk/TwelveMonkeys/files/869509/Tiffs.zip)

**Comment by haraldk** [comment]
Thanks,

I think you don't need to use or specify the destination type at all. As the docs says, it's only useful for specifying the color model if you are also specifying source bands (ie, you need a different color model, because you are stripping bands). In any case, we ignore this parameter on writing, as we don't support sub-band writing (one can always process this outside the writer so I don't think it's that useful either).

Also, explicitly setting the metadata to the default isn't necessary, as this is what happens internally in the writer when the metadata is `null`. 

With this is mind, I rewrote your `for`-loop to simply:

````java
    for (final BufferedImage image : images) {
        ImageWriteParam param = imageWriter.getDefaultWriteParam();
        param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
        param.setCompressionType("CCITT T.6");
        imageWriter.writeToSequence(new IIOImage(image, null, null). param);
    }
````

And I still get the same problem.

Somehow, the CCITT reading code is more lenient than other decoders, so the image is "read" but comes out all black. For all other relevant compressions I have tried (LZW, Deflate/ZLib and PackBits), I get `IOException`s (`DecodeException`, `ZipException` and `EOFexception`, respectively). So I'm pretty sure you have discovered a bug in the multipage writing. :-)

I still think it's related to the offsets/byte counts though, as it's unlikely that all the compressions are broken, and only for multipage. Non-compressed writing computes the offsets/byte counts differently, so this is likely why that works.


-- 
Harald K

**Comment by haraldk** [comment]
A potential fix for the problem is to change the `writeToSequence` method as follows:

````java
    @Override
    public void writeToSequence(IIOImage image, ImageWriteParam param) throws IOException {
        if (!writingSequence) {
            throw new IllegalStateException("prepareWriteSequence() must be called before writeToSequence()!");
        }

        if (sequenceLastIFDPos > 0) {
            imageOutput.seek(sequenceLastIFDPos);
            imageOutput.flushBefore(sequenceLastIFDPos);
        }

        sequenceLastIFDPos = writePage(sequenceIndex++, image, param, sequenceTIFFWriter, sequenceLastIFDPos);
    }
````

To reposition the stream before writing the next page.

-- 
Harald K

**Comment by Schmidor** [comment]
This issue might has been introduced with the refactored metadata writing.

When seeking to _sequenceLastIFDPos_ the metadata writer overwrites the IFD pointer instead of writing after the pointer.
I propose to use `imageOutput.seek(imageOutput.length());` as there could already be some image data after the IFD pointer which also should not be overwritten.

**Comment by jansohn** [comment]
In which release will this fix be included and do you already have a timeline for it?

**Comment by haraldk** [comment]
@jansohn It's in the current master, if you build yourself. Otherwise, it will be in the 3.4 release. 
Can't make any promises, other than "as soon as possible". 

-- 
Harald K

**Comment by NicoPrenzel** [comment]
Hello,

we're in progress to switch our whole image processing stuff to the Twelvemonkey ImageIO library. During this progress we've discovered a similar bug to this one. We've compiled our own library from current master (version 3.4).

The problem could be summarized like this: "Every time we try to save images into one multipage tiff image with compression standards for all pages (e.g. G3, G4 or LZW), the first page looks fine, but further pages look garbled (or black)." Mixing the compression standards results in the same issue.

Examples illustrates two b/w images that get merged, producing the issue discribed above:

private void testTwelveMonkeys() throws IOException {

		BufferedImage[] images = new BufferedImage[2]; //{
        images[0] = ImageIO.read(new File(directory +  "testimage.tif"));
        images[1] = ImageIO.read(new File(directory +  "testimage2.tif"));
        ImageWriter writer = ImageIO.getImageWritersByFormatName("TIFF").next();
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try (ImageOutputStream output = ImageIO.createImageOutputStream(buffer)) {
            writer.setOutput(output);

            ImageWriteParam params = writer.getDefaultWriteParam();
            params.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);

            try {
                writer.prepareWriteSequence(null);

                params.setCompressionType("CCITT T.4");
                writer.writeToSequence(new IIOImage(images[0], null, null), params);

                params.setCompressionType("CCITT T.4");
                writer.writeToSequence(new IIOImage(images[1], null, null), params);

                writer.endWriteSequence();
            }
            catch (IOException e) {
                System.err.println(e.getMessage());
            }
        }
        
        File f = new File(directory + "output_testimages.tif");
        FileOutputStream fos = new FileOutputStream(f);
        buffer.writeTo(fos);
 
	}
`

Tifftest contains all (source & merged) files:
[Tifftest.zip](https://github.com/haraldk/TwelveMonkeys/files/1568542/Tifftest.zip)

**Comment by Schmidor** [comment]
Hi,
I can't say why LZW is not working, but for G3/G4 I can explain it.
Your second source image contains RGB data and an extra sample. The writer does no auto conversion to monochrome data, so this doesn't work.
Good thing is, TM already has a ColorModel which can be used for conversion:
```
  private static BufferedImage convertMonochrome( BufferedImage src ) {
    if (IntStream.of( src.getSampleModel().getSampleSize() ).sum() == 1) {
      return src;
    }

    BufferedImage dst = new BufferedImage( src.getWidth(), src.getHeight(), BufferedImage.TYPE_BYTE_BINARY,
        MonochromeColorModel.getInstance() );
    Graphics2D g = dst.createGraphics();
    try {
      g.setComposite( AlphaComposite.Src );
      g.setRenderingHint( RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_DISABLE );
      g.drawImage( src, 0, 0, null );
    } finally {
      g.dispose();
    }
    return dst;
  }
```

**Comment by NicoPrenzel** [comment]
Hi,
thanks for your answer.
I've tried it to convert the images to monochrom but the merge produces the same garbled image.
I've even tried to merge the testimage.tif with himself and this produces the same result, too.

Any more hints?

**Comment by Schmidor** [comment]
I'm sorry, I cannot reproduce your issue with the current master. 
Either converting the secong image to monochrome or setting "LZW" as compression does work for me.

On direct comparission my result using LZW has diffences in a few byte on the LZW stream in the second image to your output_testimages_lzw_lzw.tif, but I don't know what could have caused that.

**Comment by haraldk** [comment]
@NicoPrenzel Thanks! 

If you built from latest master, it seems we have to revisit the multipage writing. The test code you have, looks very much like the test case we use, so it should work (except the required b/w conversion as mentioned by Schmidor*). I *really* hope to sort out the latest issues and make a 3.4 release before the end of the year.

*) In this case, I need to read up on the specification to figure out what to do. Should we throw an exception in that case, as the compression is incompatible with the image data? Attempting to compress makes no sense.

-- 
Harald K

**Comment by NicoPrenzel** [comment]
@haraldk 
Yes, I've built from latest master.
Thanks for taking part to solve that issue.

Regarding your question:
Image Viewer (like Irfanview) do an automatically conversion to b/w if the compression is set to for e.g. G3/G4.
But to take into the effort for an automatically conversion, I'am absolutly fine with an "Image doesn't fit to compression setting" exception.

@Schmidor 
Which version of master you've used for your tests?

**Comment by Schmidor** [comment]
Im using the latest commit and added your code as a test case to TIFFImageWriterTest
https://github.com/haraldk/TwelveMonkeys/commit/5a27048600d82e6a0446f904cc204f1ff2d84d7f
`    @Test
    public void testTwelveMonkeys() throws IOException {
        String directory = "C:\\Temp\\Tifftest\\";
        BufferedImage[] images = new BufferedImage[2]; //{
        images[0] = ImageIO.read(new File(directory +  "testimage.tif"));
        images[1] = ImageIO.read(new File(directory +  "testimage2.tif"));
        ImageWriter writer = ImageIO.getImageWritersByFormatName("TIFF").next();
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try (ImageOutputStream output = ImageIO.createImageOutputStream(buffer)) {
            writer.setOutput(output);

            ImageWriteParam params = writer.getDefaultWriteParam();
            params.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);

            try {
                writer.prepareWriteSequence(null);

                params.setCompressionType("LZW");
                writer.writeToSequence(new IIOImage(images[0], null, null), params);

                params.setCompressionType("LZW");
                writer.writeToSequence(new IIOImage(images[1], null, null), params);

                writer.endWriteSequence();
            }
            catch (IOException e) {
                System.err.println(e.getMessage());
            }
        }

        File f = new File(directory + "output_testimages.tif");
        FileOutputStream fos = new FileOutputStream(f);
        buffer.writeTo(fos);

    }`

**Comment by NicoPrenzel** [comment]
I've given it another try as @Schmidor doesn't have the garbled/corrupt tiff files. I've done all compilation of the whole Twelvemonkey ImageIO library with Orcale JDK 8, now. But the created libraries produce the same garbled tiff image.

**Comment by blueinblue** [comment]
I've run into this today too.  I'm trying to take a set of TIFFs and create a single multi-page TIFF.  I've built the latest source and recreated the example above, but the issues are still there.  If I choose compression type NONE, it works fine but the resulting multi-page TIFF is too large to be practical.  If I use PackBits, then the multi-page is created, but every page after 1 is shifted so that the left side of the image is near the center of the page and the right side appears on the left.  I tried converting the source TIFFs to grayscale, which caused the left side of the image to appear flush with the left side of the page.  Any other compression type produces black pages after the first page.  I'm on Linux.

Oddly enough, when I used LZW, the Linux Document Viewer showed black pages.  But when I loaded the multi-page tiff into GIMP, I could see that the TIFFs were actually there, visible, and properly aligned.

It'd be terrific if you could get this working, as this seems to be the only open source library that supports the creation of multi-page TIFFs.  Thanks for the time you've put into this!

**Comment by haraldk** [comment]
Hi guys,

I just pushed a modified test for multi page TIFF writing, that now tests that EVERY pixel of the output is equal to that of the input. It also tests more compression types, just for fun.

I also wrote this file to disk (which broke the build, as the directory didn't exist on the CI server :-P ), and it opens fine, and all pages display fine, in our own reader, OS X preview and Windows Photo Viewer. I really can't see anything wrong.

-- 
Harald K

**Comment by blueinblue** [comment]
I took your test and replaced the images with my own TIFFs.  I'm still seeing the first page fine and then every page after is corrupted - a black page, or noisy artifacts, or off center - depending on the compression algorithm.  I tried opening it in Windows Photo Viewer - the first page displayed, but then Photo Viewer said it couldn't read the file.

Anyway you could test using actual A5 sized document TIFFs?

**Comment by haraldk** [comment]
@blueinblue 

Okay,

Then please ZIP and attach the test files you used +  the modified test code. So far we haven't been able to reproduce the problem. Maybe this is what we need.

I prefer testing with smaller images, as that is faster. But of course, if the size matters for the correctness, I will consider using larger images. 

-- 
Harald K

**Comment by NicoPrenzel** [comment]
@haraldk 

I've compiled the Twelvemonkey ImageIO library again (with your latest changes from yesterday) and tried it again with our test case. The result is the same as before.

Attached you'll find a zip file with three files. "testimage - Kopie.tif" and "testimage.tif" are the source files. These files are a file copy of each other. I'd wanted to be absolutely sure, so I've made a copy of the source file and used them for the merge. The "output_testimages-nico.tif" is the produced file which should contain both images...

[Tifftest.zip](https://github.com/haraldk/TwelveMonkeys/files/1575248/Tifftest.zip)

**Comment by haraldk** [comment]
@NicoPrenzel I only changed the test yesterday, so I didn't expect anything to change. I'm trying to reproduce the issue you see...

For that, I also need *your code*.

-- 
Harald K

**Comment by NicoPrenzel** [comment]
@haraldk 
I've only seen some changes within the TiffImageWriter class. I've only done a simple update of my local git repository.

Our test code looks like:

private void testTwelveMonkeys() throws IOException {
		BufferedImage[] images = new BufferedImage[2];
		
        images[0] = ImageIO.read(new File(directory +  "testimage.tif"));
        images[1] = ImageIO.read(new File(directory +  "testimage - Kopie.tif"));

        ImageWriter writer = ImageIO.getImageWritersByFormatName("TIFF").next();
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();

        try  {
        	
        	ImageOutputStream output = ImageIO.createImageOutputStream(buffer);
            writer.setOutput(output);

            ImageWriteParam params = writer.getDefaultWriteParam();
            params.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);

            try {
                writer.prepareWriteSequence(null);

                params.setCompressionType("CCITT T.6");
                writer.writeToSequence(new IIOImage(convertMonochrome(images[0]), null, null), params);

                params.setCompressionType("CCITT T.6");
                writer.writeToSequence(new IIOImage(convertMonochrome(images[1]), null, null), params);

                writer.endWriteSequence();
            }
            catch (IOException e) {
                System.err.println(e.getMessage());
            }
        }
        catch (IOException e) {
            System.err.println(e.getMessage());
        }
        
        File f = new File(directory + "output_testimages-nico.tif");
        FileOutputStream fos = new FileOutputStream(f);
        buffer.writeTo(fos);
 
	}

**Comment by blueinblue** [comment]
Here's a maven/eclipse project with tiffs included.  Open the TiffServiceTest and look at the testToMultiPageTiff method to execute.

My results based on compression type:
None: Multi page tiff is created correctly, but it's too large to be practical.
PackBits: Page one is fine, all other pages are shifted to the right
LZW: Page one is fine, all other pages are black.

When you generate the multitiff on your system with PackBits/LZW, are you seeing the same thing?

[MultiTiffTest.zip](https://github.com/haraldk/TwelveMonkeys/files/1576089/MultiTiffTest.zip)

**Comment by haraldk** [comment]
No I don't... That is the weird thing. 

But finally! When I run it inside your project, I *can* reproduce the issue. After scratching my head for a while, I figured the only difference. My unit tests all run with:

    ImageIO.setUseCache(false);

(I do this because this disables disk-cache, and uses in-memory caching instead, which makes the tests run faster). If I do the same with your code, it just magically works... (or if I disable it in the tests, I can make the tests fail).

Now, it should obviously work regardless of the cache setting, so there is a bug. But I need some more time to investigate, before I can create a fix. In the mean time, feel free to disable disk caching as a workaround. :-)


Best regards,

-- 
Harald K

**Comment by blueinblue** [comment]
@haraldk 

Looking at the hex diff between the multipage tiffs produced by A) the in memory cache and B) the file cache, I see the following difference:
A)
87584   01 55 4a 00 02 9d 17 **00 00 00 00** 82 ff 82 ff c1
B)
87584   01 55 4a 00 02 9d 17 82 ff 82 ff c1 ff 00 f0 82

In the TIFFImageWriter, it looks like you write an integer 0 between each tiff as it's combined into the multi-tiff.  

`imageOutput.writeInt(0); // Update current IFD pointer later`

It seems like, for whatever reason, this isn't getting flushed to the underlying output stream before you move on to the next document when using the file cache.  Maybe this is the problematic code in the TIFFImageWriter's writePage method:

`// Update IFD0-pointer, and write IFD
        if (compression != TIFFBaseline.COMPRESSION_NONE) {
            entries.put(TIFF.TAG_STRIP_OFFSETS, new TIFFEntry(TIFF.TAG_STRIP_OFFSETS, stripOffset));
            entries.put(TIFF.TAG_STRIP_BYTE_COUNTS, new TIFFEntry(TIFF.TAG_STRIP_BYTE_COUNTS, stripByteCount));

            long ifdPointer = tiffWriter.writeIFD(entries.values(), imageOutput); // NOTE: Writer takes case of ordering tags

            nextIFDPointerOffset = imageOutput.getStreamPosition();

            // TODO: This is slightly duped....
            // However, need to update here, because to the writeIFD method writes the pointer, but at the incorrect offset
            // TODO: Refactor writeIFD to take an offset
            imageOutput.seek(lastIFDPointerOffset);
            imageOutput.writeInt((int) ifdPointer);
            imageOutput.seek(nextIFDPointerOffset);

            imageOutput.writeInt(0); // Next IFD pointer updated later
        }`

There at the end, you seek to the next ifd pointer offset, then write the 0, but you don't update the nextIFDPointerOffset, so you end up overwriting the 0 block in the next page write.  The random access stuff confuses me to no end, but hopefully this is a little bit helpful.  Thank you for your time!

**Comment by haraldk** [comment]
@blueinblue Thank you!

The IFD pointer is initially set to 0, which means there are no more IFDs. When we write a new page, we need to update this IFD pointer to the offset of the new IFD. So, the overwriting is intentional. But yes, it's somewhat complex due to how TIFF works... And it may very well be broken. 

Right now it bothers me more why the behavior is different depending on the cache setting... If there's a bug in the `ImageOuputStream` implementations, we have a problem. 

I hope to find some time today to look into this, and come up with a fix!

-- 
Harald K

**Comment by Schmidor** [comment]
If I compare the results both it seems the byte-strip is written four bytes before what is saved in the IFD as byte-strip-offset.
Those four zero-bytes are also in the working file, only after the byte-strip instead of in front of it.

**Comment by haraldk** [comment]
I just created a new test (on a different computer, I'll try to post it later), that does not write to an in-memory stream, but instead writes directly to file (using `FileImageOutputStream`, equivalent of `ImageIO.createImageOutputStream(new File(...))`). This file is identical to the one without disk cache (using `MemoryCacheImageOutputStream`), eg. good. The bad file is created using `FileCacheImageOutputStream`... 

I'm starting to lean against the theory that there is a bug in the `FileCacheImageOutputStream` implementation... :-/

-- 
Harald K

**Comment by Schmidor** [comment]
I'm not sure if this is causing the bug, but even in the working file this zero-bytes should not be necessary.
I have too further investigate this.
If I look at https://github.com/haraldk/TwelveMonkeys/blob/921dba89f79fc51550451f01c2d803651bc6ee48/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageWriter.java#L341 this write should not be necessary, as there is no IFD written and therefore no IFD0-pointer is needed here. The IFD0 pointer after the IFD for compressed images is written in https://github.com/haraldk/TwelveMonkeys/blob/921dba89f79fc51550451f01c2d803651bc6ee48/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageWriter.java#L391
But if I remove the first writeInt the bytestrip-offsets are wrong. I have to check whether this produces the same problems as we see with the FileCacheImageOutputStream.

Interestingly, all tests are passing if I remove the write from line 391 instead. But I suspect that this causes other errors.

**Comment by blueinblue** [comment]
@haraldk 
I got this working with the following small modification to the TIFFImageWriter.  The first code block below is correct and doesn't need to be modified.  I've included it as part of the explanation.  See the BiB comment:

```

if (compression == TIFFBaseline.COMPRESSION_NONE) {
            // This implementation, allows semi-streaming-compatible uncompressed TIFFs
            long streamPosition = imageOutput.getStreamPosition();

            long ifdSize = tiffWriter.computeIFDSize(entries.values());
            long stripOffset = streamPosition + 4 +  ifdSize + 4;
            long stripByteCount = (renderedImage.getWidth() * renderedImage.getHeight() * pixelSize + 7) / 8;

            entries.put(TIFF.TAG_STRIP_OFFSETS, new TIFFEntry(TIFF.TAG_STRIP_OFFSETS, stripOffset));
            entries.put(TIFF.TAG_STRIP_BYTE_COUNTS, new TIFFEntry(TIFF.TAG_STRIP_BYTE_COUNTS, stripByteCount));

            long ifdPointer = tiffWriter.writeIFD(entries.values(), imageOutput); // NOTE: Writer takes case of ordering tags
            nextIFDPointerOffset = imageOutput.getStreamPosition();

            // If we have a previous IFD, update pointer
            if (streamPosition > lastIFDPointerOffset) {
                imageOutput.seek(lastIFDPointerOffset);
                imageOutput.writeInt((int) ifdPointer);
                imageOutput.seek(nextIFDPointerOffset);
            }

            imageOutput.writeInt(0); // Update next IFD pointer later
        }
        else {
        	/*
        	 * BiB: This else statement writes the 0 placeholder to the stream.
        	 */
            imageOutput.writeInt(0); // Update current IFD pointer later
        }

```

This is the part that needs to be changed.  Notice the commented out call to the writeInt(0) at the end.  This is a duplicate call to the one above.

```
 if (compression != TIFFBaseline.COMPRESSION_NONE) {
            entries.put(TIFF.TAG_STRIP_OFFSETS, new TIFFEntry(TIFF.TAG_STRIP_OFFSETS, stripOffset));
            entries.put(TIFF.TAG_STRIP_BYTE_COUNTS, new TIFFEntry(TIFF.TAG_STRIP_BYTE_COUNTS, stripByteCount));

            long ifdPointer = tiffWriter.writeIFD(entries.values(), imageOutput); // NOTE: Writer takes case of ordering tags

            nextIFDPointerOffset = imageOutput.getStreamPosition();

            // TODO: This is slightly duped....
            // However, need to update here, because to the writeIFD method writes the pointer, but at the incorrect offset
            // TODO: Refactor writeIFD to take an offset
            imageOutput.seek(lastIFDPointerOffset);
            imageOutput.writeInt((int) ifdPointer);
            imageOutput.seek(nextIFDPointerOffset);
            
            /**
             * Bib: This if block is sort of an extension of the above else statement - both blocks get executed because we are using compression.
             * 
             * So, the line below writes another 0 placeholder.  You end up with two placeholders, but the pointer offsets do not reflect 
             * this, so the IFD pointers in the resulting tiff are incorrect.  If you remove the writeInt(0) line below, you remove the 
             * duplication.
             * 
             */
            //imageOutput.writeInt(0); // Next IFD pointer updated later
        }
```

**Comment by Schmidor** [comment]
In theory not writing this _imageOutput.writeInt(0);_ should cause writing the imageData of the next page at the IFD pointer location, as the IFD pointer location is stored in _nextIFDPointerOffset_ but the _imageOutput.getStreamPosition();_ not advanced by the size of this pointer.

**Comment by blueinblue** [comment]
@Schmidor 
Every call to imageOutput.write* advances the streamPos in FileCacheImageOutputStream, so you are always writing at the end of the file cache unless you explicitly seek elsewhere.  The logic to me looks like:

[write 00 00 00 00 placeholder for IDF location]
[write image data]
[write idf entries]
[seek back to last placeholder and overwrite 0s with actual location]
[seek to the end of the stream]
[In the error case, write the 0 placeholder again]
[In the correct case, repeat the process with the next image]
```

nextIFDPointerOffset = imageOutput.getStreamPosition();

imageOutput.seek(lastIFDPointerOffset);
imageOutput.writeInt((int) ifdPointer);
imageOutput.seek(nextIFDPointerOffset);

```
That call to getStreamPosition returns the end of the stream because every call to write has been advancing the streamPos within the FileCacheImageOutputStream.  When the above logic loops back, it writes the 00 placeholders at the end, then the image data, then the IDF, etc.

**Comment by Schmidor** [comment]
@blueinblue 
The logical structure for an IFD is [num entries][entries][pointer to next IFD or 00 00 00 00].
This is why we after any _tiffWriter.writeIFD(..)_ the pointer from the end of the previous IFD is updated and 00 00 00 00 is written after the current IFD.

If now this  "imageOutput.writeInt(0);" is removed, the pointer is still written if the next page is compressed (as there is a _imageOutput.writeInt(0);_ which currently just should be unnecessary). If no page is following the closing IFD0-pointer is missing then. If a compressed page is following I suppose some content from an IFD-entry is overwritten. Likely some text tag, as most relevant Tags are small enough to be in-place and not referenced from the IFD structure.

**Comment by blueinblue** [comment]
@Schmidor 
After looking at this more, it looks like the first call to writeInt(0) in TIFFImageWriter:
```

else {
            imageOutput.writeInt(0); // Update current IFD pointer later
}
```
is not getting flushed to the RandomAccessFile under the covers.  The pointer indicates that it has, but when you look at the temp file (and even the final combined tiff), it's not actually there.  So to the code it looks like the offsets have calculated correctly, but in reality they are four bytes greater than what's actually in the file.

This only affects the FileCacheImageOutputStream, as the MemoryCacheImageOutputStream reflects the four extra 00s created by the two calls.

It works if I change the code to:

```
else {
     imageOutput.seek(imageOutput.length());
     imageOutput.writeInt(0); // Update current IFD pointer later
}
```

I think the next IFD pointer is always written to the end of the stream, so perhaps this is okay.  I'd like to understand why the write isn't making it to the RandomAccessFile though.

**Comment by haraldk** [comment]
@blueinblue @Schmidor Thanks a lot for digging into this!

It seems you found the bug in the `FileCacheImageInputStream`, even if I still don't fully get why it happens...

I even works if I seek to the current position:

            imageOutput.seek(imageOutput.getStreamPosition());

...which clearly should not do anything. But it does somehow seem to get the stream/cache "in sync" somehow. The good thing is that this is side-effect free for the other stream implementations. 

I will create some more test cases and hopefully push a fix soon. 

---

About the extra bytes, yes I also think we write 4 bytes too much in some cases, but this just leaves innocent gaps in the file. Should cause no troubles for decoders.

-- 
Harald K

**Comment by blueinblue** [comment]
@haraldk 
I think I finally tracked down the culprit.  In the TIFFImageWriter this method:

```
@Override
    public void writeToSequence(IIOImage image, ImageWriteParam param) throws IOException {
        if (!writingSequence) {
            throw new IllegalStateException("prepareWriteSequence() must be called before writeToSequence()!");
        }

        if (sequenceLastIFDPos > 0) {
            imageOutput.seek(imageOutput.length());
            imageOutput.flushBefore(sequenceLastIFDPos);
        }

        sequenceLastIFDPos = writePage(sequenceIndex++, image, param, sequenceTIFFWriter, sequenceLastIFDPos);
    }
```

On the second invocation of this method, for writing the second page, the end of the stream contains 00 00 00 00, which was written there from the previous call to writePage.  Let's say these 00s occupy positions 46440 to 46444.  That means the sequenceLastIFDPos is equal to 46440 and the length of the stream is 46444.

During the second invocation, we seek to the end of the stream, position 46444.  But we then instruct the buffer to flush everything before the sequenceLastIFDPos, 46440.  The flush method invokes stream.read calls, which effects the pointer within the cache.  So, after the flushBefore method completes, the internal cache pointer is now at 46440.

So when we proceed to the writePage call, the first write (of the 00s) occurs at 46440, even though the code thinks it is writing at the end of the stream, 464444.  We are in effect overwriting the 00s we wrote at 46440 in the last invocation.  This overwrite occurs under the covers, within the cache, but the 12 monkeys code proceeds as though its now at 464448, with 8 bytes of 0s behind it.

I think we need to reset the position after the flush to sync the underlying cache pointer with the 12 monkeys code:

```
imageOutput.seek(imageOutput.length());
imageOutput.flushBefore(sequenceLastIFDPos);
imageOutput.seek(imageOutput.length());
```

I feel like I've finally gotten a splinter out of my eye.  Lol.

**Comment by Schmidor** [comment]
@blueinblue 
You are right, that's it!
If you compare both, FileCacheImageOutputStream and MemoryCacheImageOutputStream, the issue is in both.  The difference is for read/write calls the MemoryCacheImageOutputStream explicitly gives the current streamPos as a parameter to the underlying cache. The FileCacheImageOutputStream  doesn't do that.

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/javax/imageio/stream/FileCacheImageOutputStream.java#FileCacheImageOutputStream.write%28int%29
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/javax/imageio/stream/MemoryCacheImageOutputStream.java#MemoryCacheImageOutputStream.write%28int%29

**Comment by haraldk** [comment]
@blueinblue Excellent! Good catch! That is the bug. :-)

`FileCacheImageInputStream.flushBefore(pos)` (with `pos < streamPos`) leaves the `streamPos` out of sync with the `cache` file position (cache is left at `pos`), and thus the file becomes garbled. You/we should probably file a bug report (I just checked the OpenJDK 9 repo, it has the same bug). 

Actually, more things about `FileCacheImageInputStream` does seem a little suspicious to me... If you look at `maxStreamPos`, is kept in sync with the cache length at any time.. However, it's not used for anything, except for the `close()` method, where it is set to `cache.length()` just before it's used anyway. Seems like useless double book-keeping. Anyway...

The good thing, that makes the fix very easy; Just swap the order of the `flushBefore/seek` lines:

            imageOutput.flushBefore(sequenceLastIFDPos);
            imageOutput.seek(imageOutput.length());

(Writing tests to prevent this regression in the future, on the other hand... 😉 ) 

Again, tanks! 

--
Harald K

**Comment by haraldk** [comment]
Ok,

Merry Christmas guys!

I'm signing off for a few days now. But hopefully I'll find some time to create the new release, I still plan to make it in 2017. 😀


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Didn't exactly go as planned... But the new release is out now. Sorry for the delay.
