### ISSUE TITLE
Wrapped by: javax.imageio.IIOException: Error in PICT format: Unexpected end of File at position 59029

### ISSUE THREAD

**Issue by sukkutty** [haraldk/TwelveMonkeys#556]
With twelvemonkeys versions 3.3.2  (also tried with  latest version 3.6 thinking this could have been fixed in here) ,  we are seeing this exception on a particular image while resizing it. This sometimes resizes good but fails resizing most of the time (depends on the heap size availability is an observation)
Here is the full error :

at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:353)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.readPICTopcodes(PICTImageReader.java:1594)
	... 141 common frames omitted
Wrapped by: javax.imageio.IIOException: Error in PICT format: Unexpected end of File at position 59029
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.readPICTopcodes(PICTImageReader.java:1643)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.drawOnto(PICTImageReader.java:341)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.read(PICTImageReader.java:2496)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)

and image we are seeing trouble in resizing (sometimes) is - 
![r640](https://user-images.githubusercontent.com/29271069/89497426-adc19a00-d7ff-11ea-8ad1-0cbcd727b62a.jpeg)

We are seeing following "java.lang.OutOfMemoryError: Java heap space" as well , 
 java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.SinglePixelPackedSampleModel.createDataBuffer(SinglePixelPackedSampleModel.java:242)
	at java.awt.image.Raster.createWritableRaster(Raster.java:941)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
	at com.twelvemonkeys.imageio.ImageReaderBase.getDestination(ImageReaderBase.java:316)
	at com.twelvemonkeys.imageio.plugins.pict.PICTImageReader.read(PICTImageReader.java:2477)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)

Any help is highly appreciated

Thanks
sudha

**Comment by haraldk** [comment]
Hi Sudha,

It seems that there is a problem with the `PICTImageReaderSpi` incorrectly recognising the format as PICT (while it is in fact a JPEG). I think the reason it happens "sometimes" is that the order of the SPIs are not completely stable.

You can avoid this easily by disabling the PICT plugin (remove the `imageio-pict.jar`). If you need the PICT plugin, you can also fix it by making sure the `JPEGImageReaderSpi` is always preferred over the `PICTImageReaderSpi` (requires code).

Unfortunately, the PICT format doesn't have a well-defined header, so there might be some false positives in trying to recognise the format. I'll look into how we can make this better, but making it bullet-proof is next to impossible...


Best regards,

-- 
Harald K

**Comment by sukkutty** [comment]
Thanks you very much Harald for your prompt response, that helped us deciding on  how to go ahead atm on our current issue.  We have decided to take out imageio-pict plugin from our project as had seen no PICT formatted images have been getting processed in past month.

But We also want to look at a possible fix that you mentioned in your reply and make our service supporting PICT formatted images as well 

You have mentioned 
_" If you need the PICT plugin, you can also fix it by making sure the JPEGImageReaderSpi is always preferred over the PICTImageReaderSpi (requires code)."_  
how easy is it to make these changes ?  If it is a straight forward fix I want to try that out to support PICT image formats in our service. Can you please let me know how can I do this in best possible way? 

Thank you
Sudha

**Comment by haraldk** [comment]
Great!

We can't easily make those changes to the library, as the plugins (Spi classes) may be registered in any order initially. But you can do this in your application code, please see [this SO answer](https://stackoverflow.com/a/38198991/1428606) for how to set explicit order for the Spi classes. 

I am also working on making the `PICTImageReaderSpi` stricter, by checking for known formats like JPEG, PNG, TIFF etc, to avoid many false positives.


-- 
Harald K

**Comment by haraldk** [comment]
Fixed in bda6544

**Comment by sukkutty** [comment]
Hi Harald, 
We tried suggested fix for getting PICt spi lower preference over jpeg SPI but somehow it still gets issues around it.
Meantime I want to take out fix (possible upgrade to latest version as well) and test all images if they all get read without any issue. 

How can I get your fix in my project? whats the version I should be mentioning in my pom dependancy ?

**Comment by haraldk** [comment]
> We tried suggested fix for getting PICt spi lower preference over jpeg SPI but somehow it still gets issues around it.

What "issues" are you talking about here? The same ones? Are you sure you have the correct order of the SPIs?

to get the fix, it depends on what version you currently have. If you have the latest (3.6), you should be able to just build the PICT plugin from source, and use it (you might want to create a 3.6-SPIFix version, to depend on in your project). 

For an earlier version, check out the version you are using, and cherry pick bda6544 into that branch before building. It should work if you're on a recent version.


-- 
Harald K
